
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  build_app(scheme: "StoriesSDK",
            workspace: "StoriesSDK.xcworkspace",
            include_bitcode: true)
    # upload_to_testflight
  end
end

