
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :beta do
  build_app(scheme: "StoriesSDK",
            workspace: "StoriesSDK.xcworkspace",
            include_bitcode: true)
slack(message: "Successfully distributed a new beta build")
    # upload_to_testflight
  end

lane :release do
  sigh(
        development:false,
        skip_certificate_verification:true
      )

      gym(
        scheme: "StoriesSDK",
        workspace: "StoriesSDK.xcworkspace",
        output_directory: ".",
        archive_path:".",
        configuration: "Release",
        export_method: "app-store",
        export_options: {
          provisioningProfiles: {
            "co.opendigi.openbook" => "/.github/secrets/Open_Dev_Profile.mobileprovision.gpg"
          }
        }
      )
  end


lane :setup do
  build_app(scheme: "StoriesSDK",
            workspace: "StoriesSDK.xcworkspace",
            include_bitcode: true)
end

end

