name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test :

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
        
    - name: Install Pods
      run: |
        pod install

    - name: Build and test
      run: xcodebuild clean build test -workspace StoriesSDK.xcworkspace -scheme "StoriesSDK" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
      
    - name: Install gpg
      run: brew install gnupg
      
    - name: Setup provisioning profile
    env:
        IOS_KEYS: ${{ secrets.IOS_KEYS }}
    run: ./.github/secrets/decrypt_secrets.sh
