name: Build iOS

on:
push:
    branches:
    - master

jobs:
build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Switch XCode Version
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app

    - name: Get dependencies
      run: source .github/ios/build.sh && get_dependencies

    - name: Decrypt secrets
      run: source .github/ios/build.sh && decrypt_secrets ${{ secrets.SECRET_KEY }}
      env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Set up code signing
      run: source .github/ios/build.sh && setup_code_signing

    - name: Build app
      run: source .github/ios/build.sh && build_app

    - name: Upload artifacts
      run: source .github/ios/build.sh && upload_artifacts
